Implement power spectrum normalization and include it in SVD pipeline closes #14
flatironinstitute/Cryo-EM-Heterogeneity-Challenge-1 pull request #15
Opened 2024-05-31 17:55 UTC by DSilva27

Included power spectrum normalization in `_preprocessing/normalize.py`. I included functions to compute power spectrum and also to normalize a set of volumes. Tried to use NUFFT for a better estimation of the power spectrum, but I couldn't manage to go back to real space. I think you are not supposed to go back anyway, as the adjoint transform is not necessarily the inverse transform. If you know how to revert NUFFT, then I would prefer to implement the normalization using that.

2024-06-13 07:08 UTC, DavidHerreros requested changes
It would be nice to add to the template svd_config.yaml file the new mandatory parameters (ref_vol_key, ref_vol_index, and output_file).

Also, having a short description in the SVD jupyter notebook of those new keys might be helpful for future users. Something like:

- ref_vol_key (str): the identifier of the submission where the reference volume needed to normalize the data will be taken (such as the icecream flavour of one of the submissions)
- ref_vol_index (int): in combination with ref_vol_key, determines the volume that will be set as the reference for the normalization of the data
- output_file (path): file where the ouputs will be saved. Must have .pt extension  -  (I think output_file substitutes output_path right?)

2024-06-27 14:59 UTC, DSilva27 commented
I implemented the changes. Also, I updated the config to make it more clear that the keys are related to power spectrum normalization.

2024-07-09 17:59 UTC, geoffwoollard commented
@DSilva27 can you get the unit tests working (can be merged in from main), so I can see they pass in the PR?

2024-07-11 19:09 UTC, DSilva27 commented
Merged from main (actually, from 39-fix-small-bug-in-preprocessing-pipeline, so revise that one first). 

This PR does the following updates

**Major Changes**
- Implements power spectrum normalization using one submission as reference.

**Minor Changes**
- Fixes the script that downloads the testing data so it is all inside tests/data. Updates all tests so they are consistent with this change.
- Fixes tests generating files outside of tests/results

Closes #14 and #41

2024-07-12 00:19 UTC, geoffwoollard commented on tests/config_files/test_config_map_to_map.yaml
> +    volume: tests/data/Ground_truth/mask_dilated_wide_224x224.mrc
Remove tests from here, as it's the mask for the regular results. It agrees with the directories on OSF.

2024-07-12 00:21 UTC, geoffwoollard commented on tests/scripts/fetch_test_data.sh
> +wget https://files.osf.io/v1/resources/8h6fz/providers/dropbox/Ground_truth/mask_dilated_wide_224x224.mrc?download=true -O tests/data/Ground_truth/mask_dilated_wide_224x224.mrc
remove tests from here to be consistent.

2024-07-12 00:23 UTC, geoffwoollard commented on tutorials/2_tutorial_svd.ipynb
Strongly suggested: Include rendered plots (low dpi) in this showing some results. People can compare against this when they reproduce things locally.

2024-07-12 00:24 UTC, geoffwoollard commented on tutorials/3_tutorial_map2map.ipynb
what did you change in this?

2024-07-12 00:24 UTC, geoffwoollard commented on tutorials/4_tutorial_distribution2distribution.ipynb
what did you change in this?

2024-07-12 00:25 UTC, geoffwoollard requested changes
Wow that's a lot of work, good job. Almost there.

I really things some SVD plots would help serve as documentation.

2024-08-05 12:28 UTC, geoffwoollard commented
@DSilva27 There are some merge conflicts to attend to. But after that, since all the tests are passing, why don't you merge this in?

2024-08-05 22:27 UTC, DSilva27 commented
Making an overhaul of how the normalization is done. Will close this for now.

2024-08-05 22:27 UTC, closed without merging